title: My Personal Blog
description: A blog about my journey.
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache # <-- Add this line

paginate: 10
paginate_path: '/page:num/'
