title: My Personal Blog
description: A blog about my journey.
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Add these lines for Chirpy's pagination:
paginate: 10
paginate_path: '/page:num/'
