title: average-us blog
description: blog about my journey
remote_theme: mmistakes/minimal-mistakes
repository: "average-us/average-us.github.io"

url: "https://github.io"
baseurl: ""

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

paginate: 10
paginate_path: '/page:num/'
